version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - server/.env
    environment:
      - NODE_ENV=production
    ports:
      - '8080:8080'
    networks:
      - appnet
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - VITE_SERVER_URL=http://server:8080
    depends_on:
      - server
    ports:
      - '5173:5173'
    networks:
      - appnet
networks:
  appnet:
    driver: bridge