version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - server/.env
    ports:
      - '8080:8080'
    volumes:
      - ./:/workspace
    working_dir: /workspace/server
    command: ["npm", "run", "dev"]
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '5173:5173'
    environment:
      - VITE_SERVER_URL=http://localhost:8080
    volumes:
      - ./:/workspace
    working_dir: /workspace/client
    command: ["npm", "run", "dev", "--", "--host"]